### ISSUE TITLE
Artboard naming

### ISSUE THREAD

**Issue by alexrus1611** [jacopocolo/changelog.sketchplugin#1]
Is there a way we can reference the Artboard not by the fixed name 'changelog' but by a name that contains 'changelog' on a current page? This way we can have multiple changelogs on multiple pages in Sketch for example 'changelog components', 'changelog colors' or 'changelog ticket_no'

Thanks a bunch for the plugin! It is super useful and I really really appreciate your help! I made the whole 'changelog' artboard as a symbol and have them indexed in a separate page where I have tens of them. Unfortunately they are all named the same and there's no way for me to differentiate between them.

**Comment by jacopocolo** [comment]
This is something I’m struggling with myself (especially when using sketch runner to jump to specific artboards), I’ll definitely fix it in the next release. Adding the artboard name where it comes from seems very reasonable. 

By the way: I’m super interested in this approach you are using, turning changelogs into symbols. If you have time, send me and email (jacopo.colo@gmail.com) and explain it a little bit more?

**Comment by jacopocolo** [comment]
This issue should be fixed in 0.2. I did some testing and it seems to work fine: the changelog name will be updated with the name of the page it belongs to (similarly to the title of the artboard). Feel free to open another issue if this doesn’t solve your problem ;)
