### ISSUE TITLE
Form in dialog is missing.

### ISSUE THREAD

**Issue by mipmip** [jacopocolo/changelog.sketchplugin#3]
![schermafbeelding 2017-09-05 om 11 42 10](https://user-images.githubusercontent.com/658612/30055290-44c8026e-922f-11e7-8193-9fe5776cd405.png)

**Comment by jacopocolo** [comment]
Hi @mipmip, what version of Sketch are you using? I’m running Sketch 46.2 and I can't replicate the issue. 

Could you also try to do the following: 
- right click in the white area
- select “Inspect Elements”
- close the Changelog window
- go to the Console tab and tell me what it says?

Thanks!
